### ISSUE TITLE
ModuleNotFoundError: No module named pandas

### ISSUE THREAD

**Issue by joe0750** [MatthewBCooke/Pathfinder#17]
Hello,

I have gotten pathfinder installed.  When I type pathfinder, I get this:
Traceback (most recent call last):
  File "/home/joe0750/miniconda3/bin/pathfinder", line 5, in <module>
    from SearchStrategyAnalysis.Pathfinder import main
  File "/home/joe0750/miniconda3/lib/python3.10/site-packages/SearchStrategyAnalysis/__init__.py", line 1, in <module>
    from SearchStrategyAnalysis.appTrial import Trial, Experiment, Parameters, saveFileAsExperiment, Datapoint
  File "/home/joe0750/miniconda3/lib/python3.10/site-packages/SearchStrategyAnalysis/appTrial.py", line 17, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by MatthewBCooke** [comment]
Make sure you install all the requirements. We recommend using a conda virtual environment to manage the requirements for Pathfinder.
